# Setup
title:        Fratelli
tagline:      "a men's chorus"
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       "Phill Conrad"
  url:        "email:pconrad.cis@gmail.com"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown